@echo off
rem Autostart coload at logon for the current user, no admin needed:
rem drops a tiny launcher into the user's Startup folder that runs
rem coload-serve-hidden.vbs (which starts the gateway with no window).
rem Run uninstall-autostart.cmd to remove.
setlocal
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "TARGET=%~dp0coload-serve-hidden.vbs"
> "%STARTUP%\coload-autostart.vbs" (
  echo ' Auto-generated by coload install-autostart.cmd
  echo CreateObject^("WScript.Shell"^).Run "wscript.exe ""%TARGET%""", 0, False
)
if not exist "%STARTUP%\coload-autostart.vbs" (
  echo Failed to write the Startup launcher.
  exit /b 1
)
echo Installed: %STARTUP%\coload-autostart.vbs
echo Starting coload now...
wscript.exe "%TARGET%"
endlocal
